services:
  db:
    image: pgvector/pgvector:pg18-trixie
    environment:
      POSTGRES_DB: maxkb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql
  redis:
    image: redis:7-alpine
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes

volumes:
  db-data:
  redis-data: